version: '3.3'
services:
  php:
    build: ./docker
    volumes:
      - "./src:/var/www/html"

  nginx:
    image: nginx:latest
    volumes:
      - "./src:/var/www/html"
      - "./nginx/conf.d:/etc/nginx/conf.d"
    ports:
      - "80:80"