---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
  - name: Example assertion                       # выполняет проверку утверждения "that: true" на всех хостах в группе "all"
    assert:
      that: true

  - name: Check if apache2 package is installed   # проверяет установлен ли пакет apache2 
    apt:
      name: apache2
      state: present
    register: apache2_installed

  - name: Print result                            # выводит сообщение о том установлен пакет apache2 или нет
    debug:
        msg: "Apache2 is installed"
    when: apache2_installed.changed == False
